Development
aamalik/palsplate-backend pull request #2
Opened 2017-06-19 21:59 UTC by musaeed

Full authorization feature supporting Oauth2.0 protocol + cleaned up some un-polished and un-needed code.

2017-06-20 11:41 UTC, yar-malik requested changes

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/Config/OAuth2Configuration.java
> +/**
please remove the names comments on top. Its just redundant. With modern tools, you know who wrote the code.

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/Config/OAuth2Configuration.java
> +            http
identations!

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/Config/OAuth2Configuration.java
> +        private static final String PROP_CLIENTID = "clientid";
are these default values.
Avoid hardcoding.

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/Config/SecurityConfiguration.java
> +        public GlobalSecurityConfiguration(){
dont need an empty constructor, if no other constructor has been defined.

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/security/AccountUserDetailsService.java
> +    private LoginDao accountRepository;
non-intuitive name. I would never guess that accountRepository is a loginDao instance.

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/security/Authorities.java
> +    ROLE_ANONYMOUS,
we dont need anonymous or admin. We have only one user. Nobody has admin rights.

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/security/Authority.java
> +    @Size(min = 0, max = 50)
should be controlled in database end. Lets keep a standard. 
Either we do it here or we do it at database end.

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/security/CustomLogoutSuccessHandler.java
> +            OAuth2AccessToken oAuth2AccessToken = tokenStore.readAccessToken(token.split(" ")[0]);
Can a token be generated with multiple spaces?

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/config/SqlInitialization.java
> +        String PALSPLATE_DB_URL = "postgres://vrwuksarnhwksl:94a6d7413fcd44094beab4b6b2d4ef0ee2dfe4b5caecf9a3d35e17b6bf6eab5b@ec2-79-125-2-69.eu-west-1.compute.amazonaws.com:5432/dbnane6c19acb5";
We both did this. Lets remove it, one day.

2017-06-20 11:41 UTC, yar-malik commented on src/main/resources/application.properties
> +authentication.oauth.tokenValidityInSeconds=1800
30 min? Its too much. Lets make it 5 min

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/persistence/PersonDao.java
> +
?

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/config/SqlInitialization.java
>          String dbUrl = "jdbc:postgresql://" + dbUri.getHost() + ':' + dbUri.getPort() + dbUri.getPath() + "?sslmode=require";
redundant. please remove. Play around with PALSPLATE_DB_URL

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/persistence/LoginDao.java
> +import com.jersey.representations.Person;
remove

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/persistence/LoginDao.java
> +import java.util.Optional;
remove

2017-06-20 11:41 UTC, yar-malik commented on src/main/java/com/jersey/persistence/PersonDao.java
> +import org.springframework.data.jpa.repository.Query;
remove

2017-06-20 11:41 UTC, aamalik commented on src/main/java/com/jersey/persistence/LoginDao.java
> +    @Query("SELECT u FROM Login u WHERE LOWER(u.username) = LOWER(:username)")
why do you need this? 
Cant you create a method in LoginResource. What is the benefit of this @Query.
Do educate me on this matter.

2017-06-20 11:45 UTC, aamalik commented
Closing the pull request

2017-06-20 11:45 UTC, closed without merging

2017-06-20 12:17 UTC, aamalik commented on src/main/java/com/jersey/persistence/LoginDao.java
> +    @Query("SELECT u FROM Login u WHERE LOWER(u.username) = LOWER(:username)")
i think you are most probably right here.

2017-06-20 12:20 UTC, aamalik commented on src/main/java/com/jersey/persistence/LoginDao.java
> +    @Query("SELECT u FROM Login u WHERE LOWER(u.username) = LOWER(:username)")
Your approach is right. I looked at some cool project codes and thats how they do it. Cheers. Query can do really complicated stuff.

2017-07-01 19:49 UTC, musaeed commented on src/main/java/com/jersey/Authorization/Config/OAuth2Configuration.java
> +/**
I didn't add them, they were automatically added by the ide :D

2017-07-01 19:53 UTC, musaeed commented on src/main/java/com/jersey/Authorization/Config/OAuth2Configuration.java
> +            http
fixed

2017-07-01 19:53 UTC, musaeed commented on src/main/java/com/jersey/Authorization/Config/OAuth2Configuration.java
> +        private static final String PROP_CLIENTID = "clientid";
didn't find any other way until now

2017-07-01 19:55 UTC, musaeed commented on src/main/java/com/jersey/Authorization/Config/SecurityConfiguration.java
> +        public GlobalSecurityConfiguration(){
Doesn't compile without it

2017-07-01 19:57 UTC, musaeed commented on src/main/java/com/jersey/Authorization/security/AccountUserDetailsService.java
> +    private LoginDao accountRepository;
fixed

2017-07-01 19:58 UTC, musaeed commented on src/main/java/com/jersey/Authorization/security/Authorities.java
> +    ROLE_ANONYMOUS,
removed

2017-07-01 19:59 UTC, musaeed commented on src/main/java/com/jersey/Authorization/security/Authority.java
> +    @Size(min = 0, max = 50)
removed

2017-07-01 20:00 UTC, musaeed commented on src/main/java/com/jersey/Authorization/security/CustomLogoutSuccessHandler.java
> +            OAuth2AccessToken oAuth2AccessToken = tokenStore.readAccessToken(token.split(" ")[0]);
nope

2017-07-01 20:00 UTC, musaeed commented on src/main/java/com/jersey/config/SqlInitialization.java
> +        String PALSPLATE_DB_URL = "postgres://vrwuksarnhwksl:94a6d7413fcd44094beab4b6b2d4ef0ee2dfe4b5caecf9a3d35e17b6bf6eab5b@ec2-79-125-2-69.eu-west-1.compute.amazonaws.com:5432/dbnane6c19acb5";
haha yeah

2017-07-01 20:01 UTC, musaeed commented on src/main/java/com/jersey/config/SqlInitialization.java
>          String dbUrl = "jdbc:postgresql://" + dbUri.getHost() + ':' + dbUri.getPort() + dbUri.getPath() + "?sslmode=require";
this is not from me, maybe you can do it in your next change?

2017-07-01 20:02 UTC, musaeed commented on src/main/resources/application.properties
> +authentication.oauth.tokenValidityInSeconds=1800
This means if a user stays on the site for more than 5 min, they will be logged out. 30 min is very reasonable.

2017-07-01 20:02 UTC, musaeed commented on src/main/java/com/jersey/persistence/PersonDao.java
> +import org.springframework.data.jpa.repository.Query;
done

2017-07-01 20:03 UTC, musaeed commented on src/main/java/com/jersey/persistence/LoginDao.java
> +import com.jersey.representations.Person;
removed

2017-07-01 20:03 UTC, musaeed commented on src/main/java/com/jersey/persistence/LoginDao.java
> +import java.util.Optional;
done

2017-07-01 20:04 UTC, musaeed commented on src/main/java/com/jersey/persistence/LoginDao.java
> +    @Query("SELECT u FROM Login u WHERE LOWER(u.username) = LOWER(:username)")
yup

2017-07-03 10:38 UTC, aamalik commented on src/main/resources/application.properties
> +authentication.oauth.tokenValidityInSeconds=1800
okay yea. We can always easily change it later.