added pagination support
aamalik/palsplate-backend pull request #55
Opened 2017-11-14 21:03 UTC by musaeed

2017-11-15 10:38 UTC, yar-malik requested changes
Please write the cases where string is not what we asked for. We should get appropriate error

2017-11-15 10:38 UTC, yar-malik commented on src/main/java/com/jersey/Authorization/security/UserPermissionEvaluator.java
> +        Cook cook = cookDaoRepositoryFactory.getObject().findOne(ID);
whats the difference here?

2017-11-15 10:38 UTC, yar-malik commented on src/main/java/com/jersey/resources/CookResource.java
> +                } else {
Please correct the indentation  ?

2017-11-15 19:25 UTC, musaeed commented on src/main/java/com/jersey/Authorization/security/UserPermissionEvaluator.java
> +        Cook cook = cookDaoRepositoryFactory.getObject().findOne(ID);
I think i used the wrong one last time, doesn't matter too much tho, i'm using findone at other places so just to be consistent

2017-11-16 04:14 UTC, yar-malik approved these changes

2017-11-16 04:14 UTC, merged